### ISSUE TITLE
During a package installation with More > Install processes, if the action do not go to the end (bug, exceptions, etc.), go back  to the initial state

### ISSUE THREAD

**Issue by servoz** [populse/populse_sandbox#17]
at least remove the copied directories/files in the processes directory and the added lines in  the process_config.yml

**Comment by dhrbn** [comment]
Could you please remind me in which case such a thing could happen? I wanted to use something like "try: *all the install function* except ATypeOfError: *reset to the initial state*", but I have no idea what kind of error could be raised... For now I just use "except:" even if it is not really clean.

**Comment by dhrbn** [comment]
I have just added a method called install_bis in the InstallProcesses class (cf. https://github.com/populse/populse_sandbox/commit/e2c30b8526d015d038a426afef17d7a5cde2f8b9). I am pretty sure that there will be some merge conflicts after you're done with issues #8 and #11 @servoz so I will wait to merge install_bis with install.

**Comment by servoz** [comment]
OK ! I currently play exactly with the install() method of the InstallProcesses(QWidget) class. When I will finish,  we will see how to push my last commit

**Comment by dhrbn** [comment]
Normally there will be no problem because I have created a new method install_bis. I think we should meet when you are finished to be sure to merge both changes correctly

**Comment by servoz** [comment]
I  start to play with #8. I will push my next commit after you have merged install() and install_bis. Give me a shout!

**Comment by dhrbn** [comment]
I'm currently working on it! It will be fine in about 10 minutes!

**Comment by dhrbn** [comment]
I've just pushed on master. I couldn't make a lot of test because it's hard to reproduce a bug with it... (cf. https://github.com/populse/populse_sandbox/commit/16c7a673a0c00a8930bcfc70034143075d752174)
