### ISSUE TITLE
Go further with MATLAB/SPM use

### ISSUE THREAD

**Issue by dhrbn** [populse/populse_sandbox#23]

**Comment by dhrbn** [comment]
Using Matlab scripts (without standalone) and SPM standalone for the same pipeline

**Comment by dhrbn** [comment]
Go further with environment variables with Nipype
Define FORCE_SPMMCR & SPMMCRCMD just before running

**Comment by dhrbn** [comment]
For Matlab/SPM (non-standalone), the spm12 path NEEDS to be in the MATLABPATH environment variable

**Comment by servoz** [comment]
WTF  ?

**Comment by servoz** [comment]
Good job !
