### ISSUE TITLE
Add a waitbar in PackageLibrary when clicking on "Add package" (nipype importation can be long)

### ISSUE THREAD

**Issue by dhrbn** [populse/populse_sandbox#28]

**Comment by dhrbn** [comment]
I've added a status label in the PackageLibrary rather than a waitbar (cf. https://github.com/populse/populse_sandbox/commit/db66b1816bd0634744e2fcc1c210f8a4a47125fd). If it is ok for you @servoz I will close this issue.

**Comment by servoz** [comment]
Just a reminder: add also a status label when Package Library is uninstalled (avoid to be in a false situation <as we discussed yesterday>)

**Comment by servoz** [comment]
https://github.com/populse/populse_mia/commit/894a9fdaefc6fcb470d87a3c8dae49fb72bba8a6 closed this issue
