### ISSUE TITLE
Activate this repo on Travis

### ISSUE THREAD

**Issue by ouvrierl** [populse/populse_sandbox#3]
I am starting to write tests for MIA, but I do not have the rights to activate this repo on Travis.

Can an admin do it please?

Thanks!

**Comment by servoz** [comment]
is it right now ?

**Comment by ouvrierl** [comment]
Yes thank you

**Comment by ouvrierl** [comment]
populse_db seems deactivated in Travis now, the tests are not launched at every push like before.

**Comment by ouvrierl** [comment]
Yes apparently, thanks!
